"""add attendance_otp, otp_generated_at, otp_expiry, attendance_status to Shift

Revision ID: 02c222944b40
Revises: 3d950f9da462
Create Date: 2025-06-06 11:48:48.463862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c222944b40'
down_revision = '3d950f9da462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_otp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_generated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('otp_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('attendance_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_column('attendance_status')
        batch_op.drop_column('otp_expiry')
        batch_op.drop_column('otp_generated_at')
        batch_op.drop_column('attendance_otp')

    # ### end Alembic commands ###
