"""empty message

Revision ID: 0ac14c1bd018
Revises: fbc7fe470c32
Create Date: 2025-06-08 17:15:32.558647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac14c1bd018'
down_revision = 'fbc7fe470c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_assignment', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
