"""empty message

Revision ID: 28e514d5a039
Revises: 38c11db937c9
Create Date: 2025-06-07 09:19:45.101629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e514d5a039'
down_revision = '38c11db937c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkin_otp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('checkin_otp_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_column('checkin_otp_expiry')
        batch_op.drop_column('checkin_otp')

    # ### end Alembic commands ###
