"""add staff to CleaningLog

Revision ID: 3d950f9da462
Revises: 40b7f7d31c1a
Create Date: 2025-06-03 08:20:05.517937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d950f9da462'
down_revision = '40b7f7d31c1a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_cleaning_log_staff',  # ADD CONSTRAINT NAME HERE
            'staff',
            ['staff'],
            ['id']
        )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('staff')

    # ### end Alembic commands ###
