"""add staff to CleaningLog

Revision ID: 45ff699d7405
Revises: b9fe16d8951a
Create Date: 2025-06-03 04:52:04.591843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ff699d7405'
down_revision = 'b9fe16d8951a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'staff', ['staff'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('staff')

    # ### end Alembic commands ###
