"""empty message

Revision ID: 55e1d5f82d0a
Revises: 490bb0d3bb03
Create Date: 2025-06-06 15:25:38.645844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e1d5f82d0a'
down_revision = '490bb0d3bb03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.alter_column('clock_in_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('clock_in_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
