"""add cleaning_logs to Staff

Revision ID: 56b815515e9a
Revises: 46d731d470c5
Create Date: 2025-06-01 10:43:25.356445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b815515e9a'
down_revision = '46d731d470c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_log', schema=None) as batch_op:
        batch_op.alter_column('assignment_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_log', schema=None) as batch_op:
        batch_op.alter_column('assignment_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
