"""add late_checkout,    late_checkout_fee to Booking

Revision ID: 57aed1d15ed2
Revises: 55e1d5f82d0a
Create Date: 2025-06-06 21:41:45.405363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57aed1d15ed2'
down_revision = '55e1d5f82d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('late_checkout', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('late_checkout_fee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('late_checkout_fee')
        batch_op.drop_column('late_checkout')

    # ### end Alembic commands ###
