"""Add Staff to table

Revision ID: 5af82cd67a26
Revises: 
Create Date: 2025-05-28 13:04:46.268075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af82cd67a26'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'staff', ['staff'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('staff')
