"""add staff to CleaningLog

Revision ID: 709fdb919a8c
Revises: 45ff699d7405
Create Date: 2025-06-03 04:53:48.796069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709fdb919a8c'
down_revision = '45ff699d7405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'staff', ['staff'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('staff')

    # ### end Alembic commands ###
