"""Fix Staff-User relationship conflict

Revision ID: 7ef7a15a9a3d
Revises: 5af82cd67a26
Create Date: 2025-05-28 19:31:21.316667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef7a15a9a3d'
down_revision = '5af82cd67a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        # Add a name to the unique constraint
        batch_op.create_unique_constraint('uq_staff_user_id', ['user_id'])
    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        # Reference the constraint by name when dropping
        batch_op.drop_constraint('uq_staff_user_id', type_='unique')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###
