"""Add is_active to Room

Revision ID: 84d868e79e5d
Revises: dcdad291ec53
Create Date: 2025-06-14 02:16:11.421422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84d868e79e5d'
down_revision = 'dcdad291ec53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
