"""add is_rated to Rating

Revision ID: 938f32d38a63
Revises: 6b83f4607f67
Create Date: 2025-06-01 14:20:46.067938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938f32d38a63'
down_revision = '6b83f4607f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_rated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_column('is_rated')

    # ### end Alembic commands ###
