"""empty message

Revision ID: d9f4fd79119d
Revises: 0ac14c1bd018
Create Date: 2025-06-11 18:29:46.622552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f4fd79119d'
down_revision = '0ac14c1bd018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   with op.batch_alter_table('room', schema=None) as batch_op:
    batch_op.add_column(sa.Column('room_type', sa.String(length=50), nullable=False, server_default='standard'))
    batch_op.add_column(sa.Column('floor', sa.String(length=50), nullable=False, server_default='1st'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('floor')
        batch_op.drop_column('room_type')

    # ### end Alembic commands ###
