"""empty message

Revision ID: daaffb7919d3
Revises: 57aed1d15ed2
Create Date: 2025-06-06 22:08:25.255732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daaffb7919d3'
down_revision = '57aed1d15ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bar_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bar_item', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
