"""add size to Room

Revision ID: dee58bdb74d9
Revises: 938f32d38a63
Create Date: 2025-06-01 23:57:10.764136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee58bdb74d9'
down_revision = '938f32d38a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bedsize', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('bedsize')
        batch_op.drop_column('size')

    # ### end Alembic commands ###
