"""empty message

Revision ID: fbc7fe470c32
Revises: 28e514d5a039
Create Date: 2025-06-07 10:16:04.419594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc7fe470c32'
down_revision = '28e514d5a039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('available', 'reserved', 'booked', 'occupied', 'maintenance', name='room_status'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('available', 'reserved', 'booked', 'occupied', 'maintenance', name='room_status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
