"""Remove duplicate fields from Staff

Revision ID: ff8de4eb9207
Revises: 10281f82b6a7
Create Date: 2025-06-18 22:05:33.114447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8de4eb9207'
down_revision = '10281f82b6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_staff_user_id', ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_constraint('uq_staff_user_id', type_='unique')

    # ### end Alembic commands ###
